config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  namespace :admin do
    resources :videos
    resources :events
    resources :admins, only: [:index]
  end
  get 'about', to: 'pages#about'
  get 'programs', to: 'pages#programs'
  get 'news', to: 'pages#news'
  get 'index.html.var', to: 'pages#home'
  resources :events, only: [:index, :show]
  resources :videos, only: [:index]
  resources :contact, only: [:index, :new, :create]
  resources :assistance, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/assistance.rb
class Assistance < MailForm::Base
  attribute :name, validate: true
  attribute :email, validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :phone, validate: /(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}/i
  attribute :alternatecontact, validate: true
  attribute :address, validate: true
  attribute :county, validate: true
  attribute :hearfrom, validate: true
  attribute :forwho, validate: true
  attribute :incarcerated, validate: true
  attribute :program, validate: true
  attribute :helpwith, validate: true
  attribute :money, validate: true
  attribute :bank, validate: true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      subject: 'Financial Assistance Form Inquiry',
      to: 'meljcenter@gmail.com',
      from: %("#{name}" <#{email}>)
    }
  end
end

app/models/concerns/contact.rb
class Contact < MailForm::Base
  attribute :name, validate: true
  attribute :email, validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname, captcha: true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      subject: 'Contact Form Inquiry',
      to: 'meljcenter@gmail.com',
      from: %("#{name}" <#{email}>)
    }
  end
end

app/models/concerns/email.rb
class Email < MailForm::Base
  attribute :name, validate: true
  attribute :email, validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname, captcha: true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      subject: 'Contact Form Inquiry',
      to: 'meljcenter@gmail.com',
      from: %("#{name}" <#{email}>)
    }
  end
end

app/models/event.rb
class Event < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/video.rb
class Video < ApplicationRecord
  validates :title, presence: true
  # validates :url, presence: true, format: URI::regexp(/^(https?\:\/\/)?((www\.)?youtube\.com|youtu\.?be)\/.+$/)
  validates :url,
            presence: true,
            format: {
              with: /(https?\:\/\/)?((www\.)?youtube\.com|youtu\.?be)\/.+\z/,
              message: "should look like https://www.youtube.com/watch?v=W-nVrprMkvI or https://youtu.be/W-nVrprMkvI"
            }
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  before_action :find_event, only: [:show, :edit, :destroy, :update]
  before_action :event_params, only: [:create, :update]
  http_basic_authenticate_with name: ENV['ADMIN_NAME'], password: ENV['ADMIN_PASSWORD']
  def index
    @events = Event.order(updated_at: :desc)
  end

  def show
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to admin_events_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @event.update(event_params)
    redirect_to admin_events_path
  end

  def destroy
    @event.destroy
    redirect_to admin_events_path
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :image)
  end

  def find_event
    @event = Event.find(params[:id])
  end
end

app/controllers/application_controller.rb
require 'json'
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
  around_action :logging_traffic

  def default_url_options
    { host: ENV['DOMAIN'] || 'localhost:3000' }
  end

  def logging_traffic
    puts "USERAGENT: #{request.original_url}, #{request.method}"
    begin
      yield
    ensure
      puts "response_status: #{response.status}"
    end
  end
end

app/controllers/assistance_controller.rb
class AssistanceController < ApplicationController
  def index
    @assistance = Assistance.new(params[:assistance])
  end

  def create
    @assistance = Assistance.new(params[:assistance])

    @assistance.request = request
    respond_to do |format|
      if @assistance.deliver
        # re-initialize Home object for cleared form
        @assistance = Assistance.new
        format.html { render 'index' }
        format.js   { flash.now[:success] = @message = "Thank you for your message. We'll get back to you soon!" }
      else
        format.html { render 'index' }
        format.js   { flash.now[:error] = @message = 'Message did not send.' }
      end
    end
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
    @contact = Contact.new(params[:contact])
  end

  def create
    @contact = Contact.new(params[:contact])

    @contact.request = request
    respond_to do |format|
      if @contact.deliver
        # re-initialize Home object for cleared form
        @contact = Contact.new
        format.html { render 'index' }
        format.js   { flash.now[:success] = @message = "Thank you for your message. I'll get back to you soon!" }
      else
        format.html { render 'index' }
        format.js   { flash.now[:error] = @message = 'Message did not send.' }
      end
    end
  end
end

app/controllers/email_controller.rb
class EmailController < ApplicationController
  def index
    @contact = Email.new(params[:email])
  end

  def create
    @contact = Email.new(params[:email])
    @contact.request = request
    respond_to do |format|
      if @contact.deliver
        # re-initialize Home object for cleared form
        @contact = Email.new
        format.html { render 'index' }
        format.js   { flash.now[:success] = @message = "Thank you for your message. I'll get back to you soon!" }
      else
        format.html { render 'index' }
        format.js   { flash.now[:error] = @message = 'Message did not send.' }
      end
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :find_event, only: [:show]

  def index
    @events = Event.order(updated_at: :desc)
  end

  def show
  end

  private

  def find_event
    @event = Event.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
end

app/controllers/videos_controller.rb
require 'uri'
require 'cgi'

class VideosController < ApplicationController
  def index
    @videos = Video.order(updated_at: :desc)
    for i in 0... (@videos.length)
      video = @videos[i]
      query = URI(video.url).query
      params = CGI::parse(query)
      video.url = params['v'][0]
    end
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assistance_helper.rb
module AssistanceHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META['meta_title']
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META['meta_description']
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META['meta_image'])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?('http') ? meta_image : image_url(meta_image)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/admin/events/edit.html.erb
<div class="form container">
  <%= simple_form_for(@event, url: admin_event_path(@event)) do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :image, as: :file %>
    <div class="d-flex">
      <%= f.submit "Edit Event", class: "btn btn-primary w-50" %>
      <%= link_to "Back", admin_events_path, class: "btn btn-primary w-50" %>
    </div>
  <% end %>
</div>

app/views/admin/events/index.html.erb
<div class="banner2" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= image_path "banner_events.jpg"%>')">
  <div class="container banner-title">
    <h1>ADMIN PAGE EVENTS</h1>
  </div>
</div>

<div class="container">
  <%= link_to "New Event", new_admin_event_path, class: "btn btn-success w-100 my-5" %>
</div>

<div class="container events">
  <% @events.each do |event| %>
    <%= link_to admin_event_path(event) do %>
       <h2><%= event.title %></h2>
    <% end %>
  <% end %>
</div>

app/views/admin/events/new.html.erb
  <div class="form container my-5">
  <%= simple_form_for(@event, url: admin_events_path) do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :image, as: :file %>
    <div class="d-flex">
      <%= f.submit "Add Event", class: "btn btn-success w-50" %>
      <%= link_to "Back", admin_events_path, class: "btn btn-primary w-50" %>
    </div>
  <% end %>
</div>

app/views/admin/events/show.html.erb
<div class="container event my-5">
  <h1><%= @event.title %></h1>
  <h3><%= @event.description %></h3>
  <div class="image">
  <%= cl_image_tag @event.image, height: 300, width: 300, crop: :fill%>
  </div>
  <div class="d-flex">
    <%= link_to "Edit", edit_admin_event_path(@event), class: "btn btn-success w-50" %>
    <%= link_to "Delete", admin_event_path(@event), method: :delete, url: admin_event_path(@event), data: { confirm: "Are you sure?" }, class: 'btn btn-danger w-50' %>
    <%= link_to "Back", admin_events_path, class: "btn btn-primary w-50" %>
  </div>
</div>

app/views/events/edit.html.erb
<div class="container">
  <%= simple_form_for(@event) do |f| %>
    <div class="form-group">
      <%= f.input :title, class: "form-control" %>
      <%= f.input :description, class: "form-control" %>
      <%= f.input :image, class: "form-control" %>
      <%= f.submit "Edit Event", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/events/index.html.erb
<div class="banner2" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= image_path "banner_events.jpg"%>')">
  <div class="container banner-title">
    <h1>OUR EVENTS</h1>
  </div>
</div>

<div class="container events">
  <% @events.each do |event| %>
    <%= link_to event_path(event) do %>
       <h2><%= event.title %></h2>
    <% end %>
  <% end %>
</div>

app/views/events/show.html.erb
<div class="container event">
  <h1><%= @event.title %></h1>
  <h3><%= @event.description %></h3>
  <div class="image">
  <%= cl_image_tag @event.image, height: 300, width: 300, crop: :fill%>
  </div>
</div>