config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  namespace :admin do
    resources :videos
    resources :events
    resources :admins, only: [:index]
  end
  get 'about', to: 'pages#about'
  get 'programs', to: 'pages#programs'
  get 'news', to: 'pages#news'
  get 'index.html.var', to: 'pages#home'
  resources :events, only: [:index, :show]
  resources :videos, only: [:index]
  resources :contact, only: [:index, :new, :create]
  resources :assistance, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/video.rb
class Video < ApplicationRecord
  validates :title, presence: true
  # validates :url, presence: true, format: URI::regexp(/^(https?\:\/\/)?((www\.)?youtube\.com|youtu\.?be)\/.+$/)
  validates :url,
            presence: true,
            format: {
              with: /(https?\:\/\/)?((www\.)?youtube\.com|youtu\.?be)\/.+\z/,
              message: "should look like https://www.youtube.com/watch?v=W-nVrprMkvI or https://youtu.be/W-nVrprMkvI"
            }
end

app/controllers/application_controller.rb
require 'json'
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
  around_action :logging_traffic

  def default_url_options
    { host: ENV['DOMAIN'] || 'localhost:3000' }
  end

  def logging_traffic
    puts "USERAGENT: #{request.original_url}, #{request.method}"
    begin
      yield
    ensure
      puts "response_status: #{response.status}"
    end
  end
end

app/controllers/assistance_controller.rb
class AssistanceController < ApplicationController
  def index
    @assistance = Assistance.new(params[:assistance])
  end

  def create
    @assistance = Assistance.new(params[:assistance])

    @assistance.request = request
    respond_to do |format|
      if @assistance.deliver
        # re-initialize Home object for cleared form
        @assistance = Assistance.new
        format.html { render 'index' }
        format.js   { flash.now[:success] = @message = "Thank you for your message. We'll get back to you soon!" }
      else
        format.html { render 'index' }
        format.js   { flash.now[:error] = @message = 'Message did not send.' }
      end
    end
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
    @contact = Contact.new(params[:contact])
  end

  def create
    @contact = Contact.new(params[:contact])

    @contact.request = request
    respond_to do |format|
      if @contact.deliver
        # re-initialize Home object for cleared form
        @contact = Contact.new
        format.html { render 'index' }
        format.js   { flash.now[:success] = @message = "Thank you for your message. I'll get back to you soon!" }
      else
        format.html { render 'index' }
        format.js   { flash.now[:error] = @message = 'Message did not send.' }
      end
    end
  end
end

app/controllers/email_controller.rb
class EmailController < ApplicationController
  def index
    @contact = Email.new(params[:email])
  end

  def create
    @contact = Email.new(params[:email])
    @contact.request = request
    respond_to do |format|
      if @contact.deliver
        # re-initialize Home object for cleared form
        @contact = Email.new
        format.html { render 'index' }
        format.js   { flash.now[:success] = @message = "Thank you for your message. I'll get back to you soon!" }
      else
        format.html { render 'index' }
        format.js   { flash.now[:error] = @message = 'Message did not send.' }
      end
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :find_event, only: [:show]

  def index
    @events = Event.order(updated_at: :desc)
  end

  def show
  end

  private

  def find_event
    @event = Event.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
end

app/controllers/videos_controller.rb
require 'uri'
require 'cgi'

class VideosController < ApplicationController
  def index
    @videos = Video.order(updated_at: :desc)
    for i in 0... (@videos.length)
      video = @videos[i]
      query = URI(video.url).query
      params = CGI::parse(query)
      video.url = params['v'][0]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assistance_helper.rb
module AssistanceHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META['meta_title']
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META['meta_description']
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META['meta_image'])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?('http') ? meta_image : image_url(meta_image)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/about/_aboutboardchair.html.erb
<div class="container board-chair">
  <h2>LATREESE COOKE</h2>
  <div class="row board-chair-description">
    <div class="col-lg-6 col-md-12 col-sm-12">
      <iframe src="https://www.youtube.com/embed/on7MKCGNKaM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
    <div class="col-lg-6 col-md-12 col-sm-12 board-chair-text">
      <h4>
        Latreese Cooke, the MELJ Center's Founder and Executive Director has a demonstrated history of working in the civic & social organization industry. She is skilled in Research, Non-profit Organizational Management and Human Resources that include specialized expertise in Professional Ethics and Racial Disparities, Event Planning, Management, and Fundraising.
      </h4>
      <h4>
        Our Founder and Executive Director has made a quantifiable impact in her field by creating an organization of this type.  She has developed and created programs which are designed to support participants, reduce recidivism and provide a beacon of hope for those that would otherwise be hopeless.
      </h4>
    </div>
  </div>
  <div class="board-chair-text">
    <h4>
      Under Latreese’s leadership, MELJ Center has also been involved in helping to advance several different women as business owners and leaders, as well as assisting numerous up and coming organizations to become 501(C)3.  She not only encourages entrepreneurship for people who have been formerly incarcerated but will help them form a business model that will provide a basis that helps these organizations to succeed.
    </h4>
    <h4>
      Latreese was elected President of the Central Texas National Action Network (NAN), which is regarded as: “One of the leading civil rights organizations in the nation with chapters throughout the entire United States.  Founded in 1991 by Reverend Al Sharpton with a demonstrated history of working in the civic and social organization industry.
    </h4>
    <h4>
      In addition, Latreese has served on the following boards and committees:
      <ul>
        <li>Current member of the CAPCOG Criminal Justice Advisory Committee (CJAC)</li>
        <li>Texas Criminal Justice Committee</li>
        <li>Measure Austin</li>
        <li>Former City Council Member of Martindale, Texas</li>
      </ul>
    </h4>
    <h4>
      Latreese Cooke’s focus is “How can we continue to uplift others?”  Consequently, Latreese sets priority to the balance of sustaining the organization and maintaining the community’s needs.  There is no other organization in the State of Texas that serves those who have had experiences with the justice system the way that the MELJ Center, under Latreese’s direction, does.  Latreese Cooke is not only the Founder and Executive Director of MELJ, she is the heart and soul of this business, and she tirelessly supports the needs of this organization, staff and community.
    </h4>
    <h4>
      Latreese is currently pursuing a degree from St. Edward’s University for Business Administration Management.  She is also a veteran radio talk show host of a show she developed called “Iron Sharpens Iron” that airs on KAZI 88.7 FM.
    </h4>
    <h4>
      ironsharpensiron@kazifm.org
    </h4>
  </div>
</div>

app/views/about/_aboutemployees.html.erb
<div class="employees">
  <div class="container">
    <h2>Faces of MELJ</h2>
    <div class="employee-box flex-wrap">
      <div class="employee">
        <%= image_tag "latreese_cooke.jpg", class: "img-circular" %>
        <p>EXECUTIVE DIRECTOR</p>
        <p>Latreese Cooke</p>
      </div>
      <div class="employee">
        <%= image_tag "walker.jpg", class: "img-circular" %>
        <p>BOARD OF DIRECTORS - PRESIDENT</p>
        <p>Dr. Juliet E K Walker</p>
      </div>
      <div class="employee">
        <a href="https://www.bethancourtlaw.com/"><%= image_tag "briselda.jpg", class: "img-circular" %></a>
        <p>ATTORNEY</p>
        <p>Briselda Bethancourt</p>
      </div>
      <div class="employee">
        <%= image_tag "diane_beckman.jpg", class: "img-circular" %>
        <p>LMSW</p>
        <p>Diane Beckman</p>
      </div>
      <div class="employee">
        <%= image_tag "serafina_valtierra.jpg", class: "img-circular" %>
        <p>EXECUTIVE ASSISTANT</p>
        <p>Serafina Valtierra</p>
      </div>
    </div>
  </div>
</div>

app/views/admin/admins/index.html.erb
<div class="container admins">
  <h1>ADMIN PAGE</h1>
  <div class="admin-buttons">
    <%= link_to "EVENTS", admin_events_path, class: "btn btn-success w-50" %>
    <%= link_to "VIDEOS", admin_videos_path, class: "btn btn-success w-50" %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">

  <div class="container link footer-links">
    <a href="https://www.facebook.com/ME3LJCenter/"><i class="fab fa-facebook-square"></i></a>
    <a href="https://twitter.com/me3ljcenter"><i class="fab fa-twitter-square"></i></a>
    <a href="https://www.linkedin.com/company/melj-justice-center/about/"><i class="fab fa-linkedin"></i></a>
    <a href="https://www.youtube.com/channel/UCV44ch54zzfGUo5ElkSuF8A"><i class="fab fa-youtube"></i></a>
    <a href="https://www.instagram.com/me3ljcenter/"><i class="fab fa-instagram"></i></a>
  </div>

  <div class="container">
    <div class="row footer-main">
      <div class="col-lg-6 col-md-12 col-sm-12 contact">
        <h3>CONTACT</h3>
        <p class="link"><a href="https://goo.gl/maps/4h1yJFZicqs8e5uX6"><i class="fas fa-map-marker-alt"></i> 403 E. 15th Street, Austin, TX 78701</a></p>
        <p class="link"><a href="tel:+1-512-473-2525"><i class="fas fa-phone-volume"></i> +1 (512)-473-2525</a></p>
      </div>
      <div class="col-lg-6 col-md-12 col-sm-12">
        <h3>SPONSORS:</h3>
        <a href="https://www.samsclub.com/"><%= image_tag "sams-club.jpg", class: "sponsor-img"%></a>
        <a href="https://txbf.org/"><%= image_tag "texas_bar_foundation.jpg", class: "sponsor-img"%></a>
        <a href="https://www.co.bastrop.tx.us/"><%= image_tag "the-state-of-texas.jpg", class: "sponsor-img"%></a>
        <a href="https://www.walmart.com/"><%= image_tag "walmart.jpg", class: "sponsor-img"%></a>
        <a href="https://stdavidsfoundation.org/"><%= image_tag "stdavids.jpg", class: "sponsor-img-rectangular"%></a>
        <a href="https://hogg.utexas.edu/"><%= image_tag "hogglogo.jpg", class: "sponsor-img-rectangular"%></a>
      </div>
    </div>
  </div>

  <div class="footer-copyright">
    <p> © 2020 Iwona Wilk</p>
  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-lg navbar-light navbar-melj sticky-top">
    <%= link_to root_path, class: "navbar-brand" do %>
      <h1>melj</h1>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="https://www.paypal.com/donate?hosted_button_id=DZS5ERKR8U7L4&source=url">DONATE</a>
          </li>
          <li class="nav-item">
            <div class="dropdown show">
              <a class="btn dropdown-toggle nav-link" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">ABOUT</a>
              <div class="dropdown-menu" >
                <%= link_to "About us", about_path, class: "dropdown-item" %>
                <a class="dropdown-item" href="about#aboutemployees">Faces of MELJ</a>
                <a class="dropdown-item" href="about#aboutlatreese">Latreese Cooke</a>
              </div>
            </div>
          </li>

          <li class="nav-item">
            <div class="dropdown show">
              <a class="btn dropdown-toggle nav-link" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">PROGRAMS</a>
              <div class="dropdown-menu" >
                <%= link_to "All programs", programs_path, class: "dropdown-item" %>
                <a class="dropdown-item" href="programs#hope">Hope</a>
                <a class="dropdown-item" href="programs#forreal">Forreal</a>
                <a class="dropdown-item" href="programs#employment">Employment</a>
                <a class="dropdown-item" href="programs#counseling">Counseling</a>
                <a class="dropdown-item" href="programs#education">Education</a>
              </div>
            </div>
          </li>
          <li class="nav-item">
            <%= link_to "NEWS", news_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "EVENTS", events_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "VIDEOS", videos_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "CONTACT", contact_index_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "FINANCIAL ASSISTANCE", assistance_index_path, class: "nav-link" %>
          </li>
        </ul>
    </div>
</div>